Fix compilation bug introduced (#633)
Fix compilation bug introduced (#633) by PR:
https://github.com/o3de/o3de/pull/16269

The bug was:
C:/GIT/o3de/AtomSampleViewer/Gem/Code/Source/RHI/BasicRHIComponent.cpp(27,17):
error C2039: 'm_hasPipelineViewTag': is not a member of
'AZ::RPI::Pass::<unnamed-type-m_flags>'

Signed-off-by: galibzon <66021303+galibzon@users.noreply.github.com>