Fixes compilation bug:
D:/GIT/o3de/AtomSampleViewer/Gem/Code/Source/Automation/ScriptReporter.cpp(1106,74):
error C2440: 'initializing': cannot convert from
'AZ::IO::FixedMaxPathString' to
'AZStd::basic_string<char,AZStd::char_traits<Element>,AZStd::allocator>'

const AZStd::string projectPath = AZ::Utils::GetProjectPath();

Signed-off-by: garrieta <garrieta@amazon.com>